name: home
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  firebase_database: ^11.0.3
  flutter_facebook_auth: ^7.0.1
  flutter_localizations: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  intl: any
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/images/ajay.jpg
    - assets/images/img_add_line.svg
    - assets/images/img_budgeting_1.svg
    - assets/images/img_download_line.svg
    - assets/images/img_ellipse_1.svg
    - assets/images/img_exchange_funds_line.svg
    - assets/images/img_group.png
    - assets/images/img_group_498.png
    - assets/images/img_icons_home_2_1.svg
    - assets/images/img_profile_photo.png
    - assets/images/img_profile_photo_1.png
    - assets/images/img_profile_photo_64x64.png
    - assets/images/img_upload_line.svg
    - assets/images/img_vector.svg
    - assets/images/img_vector_16x12.svg

    - assets/images/img_arrow_right.svg
    - assets/images/img_icon_arrow_down.svg
    - assets/images/img_lock_2_line.svg
    - assets/images/img_mail_open_line.svg
    - assets/images/img_smartphone_line.svg
    - assets/images/img_user_6_line.svg

    - assets/images/img_icon_07.svg
    - assets/images/img_illustration_1.svg

    - assets/images/img_search.svg
    - assets/images/img_profile_photo_48x48.png
    - assets/images/aneesh.png
    - assets/images/img_arrow_left.svg
    - assets/images/img_delete_back_2_line.svg
    - assets/images/img_lines.svg
    - assets/images/img_delete_back_2_line.svg
    - assets/images/img_close_line.svg
    - assets/images/Illustration.svg
    - assets/images/img_illustration_4.svg

    - assets/images/img_facebook_f_logo_2019.svg
    - assets/images/img_google.svg
    - assets/images/img_group_10.png
    - assets/images/img_group_10.svg
    - assets/images/img_illustration_4.svg
    - assets/images/img_jordan_jo.svg
    - assets/images/img_lines.svg
    - assets/images/img_path1504.svg
    - assets/images/user.jpg

    - assets/images/img_eyeoffline.svg
    - assets/images/img_checkboxblankline.svg
    - assets/images/img_freepik_path.svg
    - assets/images/img_group_7.jpg
    - assets/images/img_group_7.svg

    - assets/images/img_group_9.svg
    - assets/images/img_group_499.png
    - assets/images/img_profile_photo_2.png
    - assets/images/img_vector_12x12.svg
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterExtraBold.ttf
          weight: 800
    - family: Sora
      fonts: 
        - asset: assets/fonts/SoraBold.ttf
          weight: 700
        - asset: assets/fonts/SoraSemiBold.ttf
          weight: 600
        - asset: assets/fonts/SoraRegular.ttf
          weight: 400
    - family: Antonio
      fonts: 
        - asset: assets/fonts/AntonioBold.ttf
          weight: 700
        - asset: assets/fonts/AntonioLight.ttf
          weight: 300
    - family: Lato
      fonts:
        - asset: assets/fonts/LatoRegular.ttf
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
